// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction.sql

package sqlc

import (
	"context"
)

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO ledger_entries (user_id, amount, type)
VALUES ($1, $2, $3)
RETURNING id, user_id, amount, type, created_at
`

type CreateLedgerEntryParams struct {
	UserID int64
	Amount int64
	Type   string
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, createLedgerEntry, arg.UserID, arg.Amount, arg.Type)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}
