// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LedgerEntry struct {
	ID        int64
	UserID    int64
	Amount    int64
	Type      string
	CreatedAt pgtype.Timestamptz
}
